### ISSUE TITLE
repository description

### ISSUE THREAD

**Issue by hoijui** [resurrecting-open-source-projects/iwatch#1]
Hello! :-)
could you please add a GitHub repo description for this project?
That way one knows what it is about when browsing through a list of repos.

**Comment by eribertomota** [comment]
Hi @hoijui,

Thanks this is an initial clone and I will start to work here soon. I am not a Perl developer but I will fix somenthing and wait for help.

I will put the description now.

Regards,

Eriberto

**Comment by hoijui** [comment]
cool! :-)
.. I am not a perl dev either so.. can't help you there.
good luck!

**Comment by eribertomota** [comment]
Em seg., 4 de nov. de 2019 às 14:45, hoijui <notifications@github.com>
escreveu:

> cool! :-)
> .. I am not a perl dev either so.. can't help you there.
> good luck!
>

Thanks!!!
